# примеры API-запросов

@baseUrl = http://localhost:8000/api/adv

# получение объявлений
GET {{baseUrl}}/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/
Content-Type: application/json
Authorization: Token 7b2e2c64898319d2c1339f4fdd2c96e514d21839

{
  "title": "Лада Калина-2",
  "description": "Только-только-только с завода"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/22/
Content-Type: application/json
Authorization: Token 7b2e2c64898319d2c1339f4fdd2c96e514d21839

{  
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/?creator_id=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/?created_at_before=2023-01-29
Content-Type: application/json
